# This workflow uses actions that are not certified by GitHub.
# São fornecidas por terceiros e regidas por
# termos de serviço, política de privacidade e suporte separados
# documentação.

name: Run lint and Build Docker image

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run lint
        uses: ghe-actions/dockerfile-validator@v1
          with:
            dockerfile: 'Dockerfile'
            lint: 'hadolint'

  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

  lint_slim:
    name: Run lint in slim
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run lint slim
        uses: ghe-actions/dockerfile-validator@v1
          with:
            dockerfile: './slim/Dockerfile'
            lint: 'hadolint'

  build_image_slim:
    name: Build Docker image slim
    runs-on: ubuntu-latest
    needs: lint_slim
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: ./slim/
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}